---
- name: Download path destiny
  file: path=/tmp/driver state=directory 
  tags:
   - wildfly
- name: Download Wildfly| Drivers JDBC MSSQL | MySQL | PostgreSQL
  get_url: url={{ item }} dest=/tmp/driver
  with_items:
    - https://mirror.e-unicred.com.br/repo/linux/wildfly/drivers/{{ wildfly_Final }}
    - https://mirror.e-unicred.com.br/repo/linux/wildfly/drivers/{{ sql_driver }}
    - https://mirror.e-unicred.com.br/repo/linux/wildfly/drivers/{{ mysql_driver }}
    - https://mirror.e-unicred.com.br/repo/linux/wildfly/drivers/{{ postgres_driver }}
  tags:
    - wildfly


- name: Install java
  yum: name=java-1.8.0-openjdk  state=present
  tags:
    - wildfly

- name : Create Group Wildfly
  group: name=wildfly  gid=1200 state=present
 
  tags:
    - wildfly

- name: Create user wilfly
  user: name=wildfly  shell=/bin/bash  uid=1200  group=wildfly state=present

  tags:
    - wildfly

- name: Unzip Wildfly
  unarchive: src=/tmp/driver/{{ wildfly_Final }} dest=/dados/ remote_src=True owner=wildfly group=wildfly
  tags:
    - wildfly

- name: Link wildfly
  file: dest=/dados/wildfly  src=/dados/{{ wildfly_Final_dir }}  state=link force=yes
  tags:
    - wildfly

- name:  Create directory for Jbdc for MSSQL
  file:  path={{ wildfly_dir }}/modules/system/layers/base/{{ item.dir }}/{{ item.name }}  state=directory owner=wildfly group=wildfly
  with_items:
    - { name: 'microsoft', dir: 'com'  }
    - { name: 'mysql',     dir: 'com'  }          
    - { name: 'postgres',  dir: 'org'  }
    - { name: 'oracle',    dir: 'com'  }

  tags:
    - wildfly

- name: Unzip  jdbc drive MySQL | MSSQL
  unarchive: src=/tmp/driver/{{ item }}  dest=/tmp/driver remote_src=True   owner=wildfly group=wildfly
  with_items:
    - "{{ mysql_driver }}"
    - "{{ sql_driver }}"
   
  tags: 
    - wildfly

- name: Copy  standalone.xml
  template: src=standalone.xml.j2 dest={{ wildfly_dir }}/standalone/configuration/standalone.xml owner=wildfly group=wildfly
  tags:
    - wildfly


- name: Copy  standalone.conf
  template: src=standalone.conf.j2 dest={{ wildfly_dir }}/bin/standalone.conf owner=wildfly group=wildfly
  tags:
    - wildfly

