---
- name: Install Packages from  Repo
  yum: name={{ item} state=present
  with_items:
    - epel-release
    - openvpn 
    - easy-rsa
    - iptables-services
  tags:
    - openvpn

- name: Change Group user openvpn
  shell:
       >
       usermod openvpn -g nobody -G nobody

 
- name: create directory | etc/wildfly
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf  
  notify: restart openvpn
  tags:
    - openvpn

- name:  Start and Enable OpenVpn
  service: name=openvpn  state=started  enabled=yes
  tags:
    - openvpn

- name: Allow Ip Forwarding
  shell:
       >
       sysctl -w net.ipv4.ip_forward=1
  tags:
    - openvpn

- name: Masquerade
  iptables:
    table: nat
    chain: postrouting
    source:  10.1.1.0/24
    out_interface:  eth0
    jump: masquerade
  tags:
    - openvpn
