---
- name: Install Packages from  Repo
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - openvpn 
    - easy-rsa
    - iptables-services
  tags:
    - openvpn

- name: Create directory Server
  file: path=/etc/openvpn/server state=directory owner=openvpn group=openvpn      

- name: Create directory Client
  file: path=/etc/openvpn/client state=directory owner=openvpn group=openvpn
 
- name: Template of config server
  template: src=server.conf.j2 dest=/etc/openvpn/server.conf mode=600 group=openvpn owner=openvpn 
  notify: restart openvpn
  tags:
    - openvpn

- name:  Start and Enable OpenVpn
  service: name=openvpn@server  state=started  enabled=yes
  tags:
    - openvpn

- name: Allow Ip Forwarding
  shell:
       >
       sysctl -w net.ipv4.ip_forward=1
  tags:
    - openvpn

- name: Masquerade
  iptables:
    table: nat
    chain: POSTROUTING
    source:  10.0.2.0/24
    out_interface:  enp0s3
    jump: MASQUERADE
  tags:
    - openvpn
